name: 'devbox installer'
description: 'Install Devbox in your CICD workflow'
branding:
  icon: 'box'
  color: 'purple'

inputs:
  project-path:  # path to folder
    description: 'Project path to devbox.json. Default to the root directory of the repository.'
    default: '.'
  enable-cache:  # 'true' or 'false'
    description: 'Caching the entire Nix store in github based on your devbox.json'
    default: 'false'
  devbox-version: # version of the devbox cli
    description: 'Specify devbox CLI version you want to pin to. Default to latest'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Workaround for permission issue
      if: inputs.enable-cache == 'true'
      shell: bash
      run: sudo chmod u+s "$(command -v tar)"

    - name: Mount nix store cache
      if: inputs.enable-cache == 'true'
      uses: actions/cache@v3
      with:
        path: |
          ~/.nix-defexpr
          ~/.nix-profile
          /nix/store
          /nix/var/nix
        key: ${{ runner.os }}-devbox-${{ hashFiles(format('{0}/devbox.json', inputs.project-path)) }}

    - name: Get devbox version
      shell: bash
      env:
        DEVBOX_USE_VERSION: ${{ inputs.devbox-version }}
      run: |
        if [[ -n $DEVBOX_USE_VERSION ]]; then
          echo "latest_version=$DEVBOX_USE_VERSION" >> $GITHUB_ENV
        else
          tmp_file=$(mktemp)
          latest_url="https://releases.jetpack.io/devbox/latest/version"
          curl --fail --silent --location --output "${tmp_file}" "${latest_url}"
          latest_version=$(cat "${tmp_file}")
          if [[ -n ${latest_version} ]]; then
            echo "Found devbox latest version ${latest_version}."
            echo "latest_version=$latest_version" >> $GITHUB_ENV
          else
            echo "ERROR: unable to find the latest devbox version."
            exit 1
          fi
        fi

    - name: Mount devbox cli cache
      id: cache-devbox-cli
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/devbox
        key: ${{ runner.os }}-devbox-${{ env.latest_version }}

    - name: Install devbox cli
      if: steps.cache-devbox-cli.outputs.cache-hit != 'true'
      shell: bash
      run: |
        DEVBOX_USE_VERSION="${{ env.latest_version }}"
        curl -fsSL https://get.jetpack.io/devbox | FORCE=1 bash

        version=$(devbox version)
        if [[ ! "$version" = "$DEVBOX_USE_VERSION" ]]; then
          echo "ERROR: mismatch devbox version downloaded. Expected $DEVBOX_USE_VERSION, got $version."
          exit 1
        fi
        sudo mv ${HOME}/.cache/devbox/bin/${version}_*/devbox /usr/local/bin/devbox

    - name: Install nix and devbox packages
      shell: bash
      run: |
        NIX_INSTALLER_NO_CHANNEL_ADD=1
        NIX_BUILD_SHELL=/bin/bash
        devbox shell --config=${{ inputs.project-path }} -- echo "Packages installed!"
